[widgets]
    [widgets.fileList]
    name='Files'
    widget="fileList"
        [widgets.fileList.icons]
        active="folderOpen.png"
        inactive="folderClosed.png"
        [widgets.fileList.callbacks]
        addFile="addFile"
        updateSelection="updateSelection"
        removeFile="removeFile"

